"""file column deleted from files model

Revision ID: 35885d55d27b
Revises: 478a5ac3c383
Create Date: 2022-09-27 16:50:17.402486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35885d55d27b'
down_revision = '478a5ac3c383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files_model', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files_model', sa.Column('file', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###
