"""empty message

Revision ID: 478a5ac3c383
Revises: 53f5b421ab7c
Create Date: 2022-09-25 12:46:23.681701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478a5ac3c383'
down_revision = '53f5b421ab7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files_model', sa.Column('file', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files_model', 'file')
    # ### end Alembic commands ###
