"""filesmodel added

Revision ID: 53f5b421ab7c
Revises: 
Create Date: 2022-09-24 11:58:03.691624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f5b421ab7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=80), nullable=False),
    sa.Column('yt_link', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('yt_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_model')
    # ### end Alembic commands ###
