"""file_path removed

Revision ID: 8e6263a4c32a
Revises: 35885d55d27b
Create Date: 2022-09-28 19:51:46.603999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6263a4c32a'
down_revision = '35885d55d27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=80), nullable=False),
    sa.Column('yt_link', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('yt_link')
    )
    op.drop_table('files_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=80), nullable=False),
    sa.Column('yt_link', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('yt_link')
    )
    op.drop_table('files')
    # ### end Alembic commands ###
